import {
  CargoRequirement,
  CharterContract,
  CharterOffer,
  FreightForecastResponse,
  MarketData,
  AppNotification,
  OptimizationResponse,
  Port,
  PortCongestionResponse,
  Vessel,
  VesselMatch,
  Voyage,
} from '@/types';

export const DEMO_VESSELS: Vessel[] = [
  {
    id: 'vessel-01',
    name: 'MV PACIFIC PIONEER',
    imo: '9784152',
    mmsi: '538007123',
    type: 'Capesize',
    dwt: 181500,
    loa: 292.0,
    beam: 45.0,
    maxDraft: 18.2,
    currentDraft: 17.8,
    yearBuilt: 2019,
    flag: 'Marshall Islands',
    ownerId: 'usr-ship-01',
    ownerName: 'Oceanic Bulk Carrier Fleet Ltd',
    isAvailable: true,
    availableFrom: '2026-09-02',
    currentPortId: 'port-haypoint',
    currentPortName: 'Hay Point Coal Terminal',
    dailyCharterRateUsd: 28500,
    fuelConsumptionMtPerDay: 42,
    aisPosition: {
      latitude: -20.5,
      longitude: 149.8,
      speedKnots: 12.8,
      headingDegrees: 310,
      status: 'Underway',
      destination: 'Paradip Port',
      eta: '2026-09-14T08:00:00Z',
      lastUpdated: new Date().toISOString(),
      isSimulated: true,
    },
  },
  {
    id: 'vessel-02',
    name: 'MV OCEAN FORTUNE',
    imo: '9842190',
    mmsi: '636018442',
    type: 'Panamax',
    dwt: 82000,
    loa: 229.0,
    beam: 32.2,
    maxDraft: 14.5,
    currentDraft: 14.1,
    yearBuilt: 2021,
    flag: 'Liberia',
    ownerId: 'usr-ship-01',
    ownerName: 'Oceanic Bulk Carrier Fleet Ltd',
    isAvailable: true,
    availableFrom: '2026-09-01',
    currentPortId: 'port-gladstone',
    currentPortName: 'Port of Gladstone',
    dailyCharterRateUsd: 19500,
    fuelConsumptionMtPerDay: 26,
    aisPosition: {
      latitude: -12.4,
      longitude: 125.6,
      speedKnots: 13.4,
      headingDegrees: 298,
      status: 'Underway',
      destination: 'Paradip Port',
      eta: '2026-09-12T14:30:00Z',
      lastUpdated: new Date().toISOString(),
      isSimulated: true,
    },
  },
  {
    id: 'vessel-03',
    name: 'MV BHARAT RATNA',
    imo: '9654128',
    mmsi: '419001289',
    type: 'Panamax',
    dwt: 78500,
    loa: 225.0,
    beam: 32.26,
    maxDraft: 14.4,
    currentDraft: 13.9,
    yearBuilt: 2018,
    flag: 'India',
    ownerId: 'usr-ship-02',
    ownerName: 'Great Eastern Shipping Co',
    isAvailable: true,
    availableFrom: '2026-09-03',
    currentPortId: 'port-singapore',
    currentPortName: 'Port of Singapore',
    dailyCharterRateUsd: 18800,
    fuelConsumptionMtPerDay: 25,
    aisPosition: {
      latitude: 5.8,
      longitude: 95.2,
      speedKnots: 11.9,
      headingDegrees: 335,
      status: 'Underway',
      destination: 'Visakhapatnam Port',
      eta: '2026-09-10T18:00:00Z',
      lastUpdated: new Date().toISOString(),
      isSimulated: true,
    },
  },
  {
    id: 'vessel-04',
    name: 'MV NORDIC TRADER',
    imo: '9512300',
    mmsi: '257008120',
    type: 'Supramax',
    dwt: 58000,
    loa: 189.9,
    beam: 32.26,
    maxDraft: 12.8,
    currentDraft: 12.4,
    yearBuilt: 2016,
    flag: 'Norway',
    ownerId: 'usr-ship-03',
    ownerName: 'Klaveness Bulk Carriers',
    isAvailable: false,
    availableFrom: '2026-09-18',
    currentPortId: 'port-paradip',
    currentPortName: 'Paradip Port',
    dailyCharterRateUsd: 15500,
    fuelConsumptionMtPerDay: 21,
    aisPosition: {
      latitude: 20.2644,
      longitude: 86.6711,
      speedKnots: 0.0,
      headingDegrees: 90,
      status: 'Discharging',
      destination: 'Paradip Port',
      eta: '2026-08-25T10:00:00Z',
      lastUpdated: new Date().toISOString(),
      isSimulated: true,
    },
  },
  {
    id: 'vessel-05',
    name: 'MV GOLDEN VOYAGER',
    imo: '9812456',
    mmsi: '352001924',
    type: 'Capesize',
    dwt: 176000,
    loa: 289.0,
    beam: 45.0,
    maxDraft: 18.0,
    currentDraft: 17.5,
    yearBuilt: 2020,
    flag: 'Panama',
    ownerId: 'usr-ship-01',
    ownerName: 'Oceanic Bulk Carrier Fleet Ltd',
    isAvailable: true,
    availableFrom: '2026-09-08',
    currentPortId: 'port-hedland',
    currentPortName: 'Port Hedland',
    dailyCharterRateUsd: 27900,
    fuelConsumptionMtPerDay: 40,
    aisPosition: {
      latitude: -18.2,
      longitude: 115.4,
      speedKnots: 13.1,
      headingDegrees: 320,
      status: 'Underway',
      destination: 'Dhamra Port',
      eta: '2026-09-16T06:00:00Z',
      lastUpdated: new Date().toISOString(),
      isSimulated: true,
    },
  },
];

export const DEMO_PORTS: Port[] = [
  {
    id: 'port-paradip',
    name: 'Paradip Port Terminal',
    code: 'IN PRT',
    country: 'India',
    latitude: 20.2644,
    longitude: 86.6711,
    channelMaxDepth: 17.5,
    maxVesselDwt: 125000,
    berthsCount: 16,
    currentVesselsInPort: 12,
    vesselsInQueue: 7,
    averageWaitingTimeHours: 34.5,
    congestionLevel: 'HIGH',
    berthUtilizationPercent: 84.5,
    berths: [
      {
        id: 'b-01',
        berthNumber: 'CB-1',
        name: 'Central Bulk Berth 1 (Mechanized Coal)',
        maxLoa: 240,
        maxDraft: 15.0,
        status: 'OCCUPIED',
        currentVesselId: 'vessel-04',
        currentVesselName: 'MV NORDIC TRADER',
        cargoType: 'Coking Coal',
        cargoQuantityMt: 55000,
        expectedDeparture: '2026-08-28T18:00:00Z',
        occupancyPercent: 100,
      },
      {
        id: 'b-02',
        berthNumber: 'CB-2',
        name: 'Central Bulk Berth 2',
        maxLoa: 260,
        maxDraft: 15.5,
        status: 'OCCUPIED',
        currentVesselName: 'MV MARITIME GLORY',
        cargoType: 'Thermal Coal',
        cargoQuantityMt: 75000,
        expectedDeparture: '2026-08-29T12:00:00Z',
        occupancyPercent: 100,
      },
      {
        id: 'b-03',
        berthNumber: 'IOB-1',
        name: 'Iron Ore Berth 1',
        maxLoa: 290,
        maxDraft: 17.1,
        status: 'AVAILABLE',
        occupancyPercent: 0,
      },
      {
        id: 'b-04',
        berthNumber: 'MPB-1',
        name: 'Multi-Purpose Berth 1',
        maxLoa: 220,
        maxDraft: 13.5,
        status: 'AVAILABLE',
        occupancyPercent: 0,
      },
    ],
  },
  {
    id: 'port-visakhapatnam',
    name: 'Visakhapatnam Port',
    code: 'IN VTZ',
    country: 'India',
    latitude: 17.6868,
    longitude: 83.2185,
    channelMaxDepth: 18.1,
    maxVesselDwt: 200000,
    berthsCount: 24,
    currentVesselsInPort: 16,
    vesselsInQueue: 4,
    averageWaitingTimeHours: 19.2,
    congestionLevel: 'MEDIUM',
    berthUtilizationPercent: 71.0,
    berths: [],
  },
  {
    id: 'port-dhamra',
    name: 'Dhamra Deepwater Port',
    code: 'IN DHA',
    country: 'India',
    latitude: 20.8286,
    longitude: 86.9747,
    channelMaxDepth: 18.0,
    maxVesselDwt: 180000,
    berthsCount: 8,
    currentVesselsInPort: 5,
    vesselsInQueue: 2,
    averageWaitingTimeHours: 12.0,
    congestionLevel: 'LOW',
    berthUtilizationPercent: 62.5,
    berths: [],
  },
  {
    id: 'port-haypoint',
    name: 'Hay Point Coal Terminal',
    code: 'AU HPY',
    country: 'Australia',
    latitude: -21.2882,
    longitude: 149.3006,
    channelMaxDepth: 19.5,
    maxVesselDwt: 220000,
    berthsCount: 4,
    currentVesselsInPort: 3,
    vesselsInQueue: 6,
    averageWaitingTimeHours: 28.0,
    congestionLevel: 'MEDIUM',
    berthUtilizationPercent: 78.0,
    berths: [],
  },
];

export const DEMO_CARGO_REQUIREMENTS: CargoRequirement[] = [
  {
    id: 'req-coal-75k',
    procurementOfficerId: 'usr-proc-01',
    procurementOfficerName: 'Capt. Rajesh Sharma',
    commodity: 'Coking Coal',
    quantityMt: 75000,
    originPortId: 'port-haypoint',
    originPortName: 'Hay Point Coal Terminal (Australia)',
    destinationPortId: 'port-paradip',
    destinationPortName: 'Paradip Port (India)',
    requiredArrivalDate: '2026-09-18',
    preferredVesselType: 'Panamax',
    minDwt: 75000,
    maxDraft: 14.5,
    laycanStart: '2026-09-01',
    laycanEnd: '2026-09-06',
    status: 'MATCHING',
    createdAt: '2026-08-25T09:30:00Z',
  },
  {
    id: 'req-ironore-120k',
    procurementOfficerId: 'usr-proc-01',
    procurementOfficerName: 'Capt. Rajesh Sharma',
    commodity: 'Iron Ore',
    quantityMt: 120000,
    originPortId: 'port-hedland',
    originPortName: 'Port Hedland (Australia)',
    destinationPortId: 'port-dhamra',
    destinationPortName: 'Dhamra Deepwater Port (India)',
    requiredArrivalDate: '2026-09-24',
    preferredVesselType: 'Capesize',
    minDwt: 120000,
    maxDraft: 17.5,
    laycanStart: '2026-09-08',
    laycanEnd: '2026-09-13',
    status: 'OPEN',
    createdAt: '2026-08-24T14:15:00Z',
  },
];

export const DEMO_FREIGHT_FORECAST: FreightForecastResponse = {
  originPort: 'Hay Point (Australia)',
  destinationPort: 'Paradip (India)',
  vesselType: 'Panamax',
  horizonDays: 14,
  currentRateUsdPerMt: 24.80,
  predictedRateUsdPerMt: 23.75,
  expectedChangePercent: -4.23,
  confidenceScore: 0.87,
  trend: 'DECREASING',
  recommendation: 'WAIT',
  recommendationDaysToWait: 3,
  reasons: [
    'Pacific Basin Panamax ballast supply increasing by 14% over next 72 hours.',
    'Bunker fuel VLSFO futures in Singapore trending downwards (-$18/MT).',
    'Port congestion at Paradip expected to ease from 34h to 21h by 04 Sept.',
    'Cargo arrival requirement window permits delaying charter confirmation by up to 4 days.',
  ],
  estimatedPotentialSavingsUsd: 78750,
  timeSeries: [
    { date: '2026-08-20', actualRate: 25.40, forecastRate: 25.40, lowerConfidenceBound: 25.40, upperConfidenceBound: 25.40 },
    { date: '2026-08-21', actualRate: 25.20, forecastRate: 25.20, lowerConfidenceBound: 25.20, upperConfidenceBound: 25.20 },
    { date: '2026-08-22', actualRate: 25.05, forecastRate: 25.05, lowerConfidenceBound: 25.05, upperConfidenceBound: 25.05 },
    { date: '2026-08-23', actualRate: 24.90, forecastRate: 24.90, lowerConfidenceBound: 24.90, upperConfidenceBound: 24.90 },
    { date: '2026-08-24', actualRate: 24.85, forecastRate: 24.85, lowerConfidenceBound: 24.85, upperConfidenceBound: 24.85 },
    { date: '2026-08-25', actualRate: 24.80, forecastRate: 24.80, lowerConfidenceBound: 24.80, upperConfidenceBound: 24.80 },
    { date: '2026-08-26 (Today)', actualRate: 24.80, forecastRate: 24.80, lowerConfidenceBound: 24.10, upperConfidenceBound: 25.50 },
    { date: '2026-08-27', forecastRate: 24.50, lowerConfidenceBound: 23.75, upperConfidenceBound: 25.25 },
    { date: '2026-08-28', forecastRate: 24.15, lowerConfidenceBound: 23.35, upperConfidenceBound: 24.95 },
    { date: '2026-08-29', forecastRate: 23.75, lowerConfidenceBound: 22.90, upperConfidenceBound: 24.60 },
    { date: '2026-08-30', forecastRate: 23.60, lowerConfidenceBound: 22.70, upperConfidenceBound: 24.50 },
    { date: '2026-08-31', forecastRate: 23.55, lowerConfidenceBound: 22.50, upperConfidenceBound: 24.60 },
    { date: '2026-09-01', forecastRate: 23.70, lowerConfidenceBound: 22.55, upperConfidenceBound: 24.85 },
    { date: '2026-09-02', forecastRate: 23.85, lowerConfidenceBound: 22.60, upperConfidenceBound: 25.10 },
  ],
  modelMetadata: {
    modelName: 'Maritime-Transformer-Freight-v4.2',
    version: '4.2.1',
    mae: 0.42,
    rmse: 0.61,
    trainingDate: '2026-08-25T00:00:00Z',
  },
};

export const DEMO_PORT_CONGESTION: Record<string, PortCongestionResponse> = {
  'port-paradip': {
    portId: 'port-paradip',
    portName: 'Paradip Port Terminal',
    currentCongestion: 'HIGH',
    predictedCongestionIn3Days: 'MEDIUM',
    currentWaitingTimeHours: 34.5,
    predictedWaitingTimeHours: 21.0,
    berthUtilizationPercent: 84.5,
    riskScore: 68,
    timeSeries: [
      { date: '2026-08-24', congestionLevel: 'HIGH', waitingTimeHours: 36.0, berthUtilizationPercent: 88.0 },
      { date: '2026-08-25', congestionLevel: 'HIGH', waitingTimeHours: 35.2, berthUtilizationPercent: 86.0 },
      { date: '2026-08-26', congestionLevel: 'HIGH', waitingTimeHours: 34.5, berthUtilizationPercent: 84.5 },
      { date: '2026-08-27', congestionLevel: 'MEDIUM', waitingTimeHours: 29.0, berthUtilizationPercent: 78.0 },
      { date: '2026-08-28', congestionLevel: 'MEDIUM', waitingTimeHours: 24.5, berthUtilizationPercent: 72.0 },
      { date: '2026-08-29', congestionLevel: 'MEDIUM', waitingTimeHours: 21.0, berthUtilizationPercent: 68.0 },
      { date: '2026-08-30', congestionLevel: 'LOW', waitingTimeHours: 16.5, berthUtilizationPercent: 62.0 },
    ],
    queueVessels: [
      { vesselName: 'MV MARITIME GLORY', imo: '9651234', arrivalDate: '2026-08-25 14:00', expectedBerthDate: '2026-08-27 06:00', cargo: 'Coal', quantityMt: 75000 },
      { vesselName: 'MV PACIFIC LEADER', imo: '9781209', arrivalDate: '2026-08-25 21:30', expectedBerthDate: '2026-08-27 18:00', cargo: 'Iron Ore', quantityMt: 90000 },
      { vesselName: 'MV VISHVA VIJAY', imo: '9845012', arrivalDate: '2026-08-26 04:00', expectedBerthDate: '2026-08-28 02:00', cargo: 'Coal', quantityMt: 68000 },
    ],
  },
};

export const DEMO_VESSEL_MATCHES: VesselMatch[] = [
  {
    vessel: DEMO_VESSELS[1], // MV OCEAN FORTUNE (Panamax, 82k DWT)
    matchScorePercent: 93,
    freightRateUsdPerMt: 23.75,
    estimatedTotalCostUsd: 1781250,
    eta: '14 Sep 2026',
    distanceNauticalMiles: 3840,
    congestionRisk: 'LOW',
    draftFit: true,
    channelDepthFit: true,
    availabilityFit: true,
    laycanCompatibility: true,
    riskCategory: 'LOW',
    recommendationBadge: 'BEST_MATCH',
    costBreakdown: {
      freightCost: 1781250,
      bunkerFuelCost: 284000,
      portCosts: 62000,
      demurrageWaitingRiskCost: 24000,
      otherVoyageCost: 18000,
    },
  },
  {
    vessel: DEMO_VESSELS[2], // MV BHARAT RATNA (Panamax, 78.5k DWT)
    matchScorePercent: 88,
    freightRateUsdPerMt: 24.20,
    estimatedTotalCostUsd: 1815000,
    eta: '12 Sep 2026',
    distanceNauticalMiles: 2950,
    congestionRisk: 'MEDIUM',
    draftFit: true,
    channelDepthFit: true,
    availabilityFit: true,
    laycanCompatibility: true,
    riskCategory: 'LOW',
    costBreakdown: {
      freightCost: 1815000,
      bunkerFuelCost: 265000,
      portCosts: 58000,
      demurrageWaitingRiskCost: 38000,
      otherVoyageCost: 15000,
    },
  },
  {
    vessel: DEMO_VESSELS[0], // MV PACIFIC PIONEER (Capesize, 181.5k DWT)
    matchScorePercent: 81,
    freightRateUsdPerMt: 25.10,
    estimatedTotalCostUsd: 1882500,
    eta: '15 Sep 2026',
    distanceNauticalMiles: 4120,
    congestionRisk: 'MEDIUM',
    draftFit: true,
    channelDepthFit: true,
    availabilityFit: true,
    laycanCompatibility: true,
    riskCategory: 'MEDIUM',
    costBreakdown: {
      freightCost: 1882500,
      bunkerFuelCost: 410000,
      portCosts: 95000,
      demurrageWaitingRiskCost: 52000,
      otherVoyageCost: 22000,
    },
  },
];

export const DEMO_OPTIMIZATION_RESPONSE: OptimizationResponse = {
  cargoRequirement: DEMO_CARGO_REQUIREMENTS[0],
  recommendedVessel: DEMO_VESSEL_MATCHES[0],
  alternativeVessels: [DEMO_VESSEL_MATCHES[1], DEMO_VESSEL_MATCHES[2]],
  aiRecommendation: {
    action: 'WAIT',
    waitDays: 3,
    headline: 'WAIT 3 DAYS BEFORE CHARTER EXECUTION',
    summary: 'ML freight forecasting indicates a 4.2% price decline over the next 72 hours with robust vessel supply in East Coast Australia.',
    confidencePercent: 87,
    expectedRateDeltaPercent: -4.2,
    potentialSavingsUsd: 78750,
    urgencyLevel: 'LOW',
    explainableReasons: [
      'Panamax freight rates on Australia-East Coast India route projected to drop from $24.80/MT to $23.75/MT.',
      'Ballast tonnage supply in Hay Point cluster has expanded by 3 vessels.',
      'Destination port waiting time at Paradip is decreasing from 34.5h to 21.0h by early September.',
      'Laycan flexibility window (01-06 Sept) easily accommodates a 3-day wait without arrival deadline risk.',
    ],
  },
};

export const DEMO_CHARTERS: CharterContract[] = [
  {
    id: 'ctr-2026-089',
    cargoRequirementId: 'req-coal-75k',
    cargoSummary: {
      commodity: 'Coking Coal',
      quantityMt: 75000,
      origin: 'Hay Point (Australia)',
      destination: 'Paradip Port (India)',
    },
    vesselId: 'vessel-02',
    vesselName: 'MV OCEAN FORTUNE',
    vesselImo: '9842190',
    procurementOfficerName: 'Capt. Rajesh Sharma',
    shipOwnerName: 'Oceanic Bulk Carrier Fleet Ltd',
    freightRateUsdPerMt: 23.75,
    totalContractValueUsd: 1781250,
    status: 'OFFERED',
    eta: '2026-09-14T08:00:00Z',
    etd: '2026-09-02T16:00:00Z',
    laycanStart: '2026-09-01',
    laycanEnd: '2026-09-05',
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-08-26T10:30:00Z',
    offers: [
      {
        id: 'ofr-101',
        charterRequestId: 'ctr-2026-089',
        shipOwnerId: 'usr-ship-01',
        shipOwnerName: 'Oceanic Bulk Carrier Fleet Ltd',
        vesselId: 'vessel-02',
        vesselName: 'MV OCEAN FORTUNE',
        vesselType: 'Panamax',
        vesselDwt: 82000,
        offeredFreightRateUsdPerMt: 23.75,
        totalOfferedCostUsd: 1781250,
        laycanStartOffered: '2026-09-02',
        laycanEndOffered: '2026-09-06',
        demurrageRatePerDayUsd: 22000,
        despatchRatePerDayUsd: 11000,
        terms: 'Gencon 1994, 2.5% Commission, 12,000 MT PWWD SHINC loading, 10,000 MT PWWD SHEX discharge.',
        status: 'PENDING',
        submittedAt: '2026-08-26T09:15:00Z',
      },
    ],
  },
  {
    id: 'ctr-2026-084',
    cargoRequirementId: 'req-ironore-120k',
    cargoSummary: {
      commodity: 'Iron Ore',
      quantityMt: 120000,
      origin: 'Port Hedland (Australia)',
      destination: 'Dhamra Port (India)',
    },
    vesselId: 'vessel-05',
    vesselName: 'MV GOLDEN VOYAGER',
    vesselImo: '9812456',
    procurementOfficerName: 'Capt. Rajesh Sharma',
    shipOwnerName: 'Oceanic Bulk Carrier Fleet Ltd',
    freightRateUsdPerMt: 18.50,
    totalContractValueUsd: 2220000,
    status: 'CONTRACTED',
    eta: '2026-09-16T06:00:00Z',
    etd: '2026-09-04T12:00:00Z',
    laycanStart: '2026-09-03',
    laycanEnd: '2026-09-07',
    createdAt: '2026-08-20T14:00:00Z',
    updatedAt: '2026-08-24T16:45:00Z',
    offers: [],
  },
];

export const DEMO_VOYAGES: Voyage[] = [
  {
    id: 'voy-2026-042',
    vesselId: 'vessel-02',
    vesselName: 'MV OCEAN FORTUNE',
    imo: '9842190',
    charterContractId: 'ctr-2026-089',
    cargoType: 'Coking Coal',
    quantityMt: 75000,
    originPort: 'Hay Point Coal Terminal',
    destinationPort: 'Paradip Port',
    departureDate: '2026-08-27T06:00:00Z',
    eta: '2026-09-14T08:00:00Z',
    currentCoordinates: [-12.4, 125.6],
    speedKnots: 13.4,
    headingDegrees: 298,
    currentMilestone: 'AT_SEA',
    milestonesProgressPercent: 42,
    totalNauticalMiles: 3840,
    remainingNauticalMiles: 2227,
    weather: {
      location: 'Timor Sea Passage',
      windSpeedKnots: 16.5,
      windDirection: 'ESE',
      waveHeightMeters: 1.8,
      visibilityNauticalMiles: 10.0,
      condition: 'Moderate Sea',
      isRiskCondition: false,
    },
    historicalPositions: [
      [-21.28, 149.30],
      [-19.10, 147.20],
      [-15.30, 138.40],
      [-12.40, 125.60],
    ],
    portCalls: [
      {
        portId: 'port-haypoint',
        portName: 'Hay Point Coal Terminal',
        operation: 'LOADING',
        eta: '2026-08-25T08:00:00Z',
        ata: '2026-08-25T07:45:00Z',
        etd: '2026-08-27T06:00:00Z',
        atd: '2026-08-27T05:30:00Z',
        waitingTimeHours: 6.5,
        turnaroundTimeHours: 45.7,
        status: 'DEPARTED',
      },
      {
        portId: 'port-singapore',
        portName: 'Singapore Eastern Anchorage',
        operation: 'BUNKERING',
        eta: '2026-09-06T12:00:00Z',
        etd: '2026-09-07T02:00:00Z',
        waitingTimeHours: 0,
        turnaroundTimeHours: 14.0,
        status: 'SCHEDULED',
      },
      {
        portId: 'port-paradip',
        portName: 'Paradip Port Terminal',
        operation: 'DISCHARGE',
        eta: '2026-09-14T08:00:00Z',
        etd: '2026-09-17T18:00:00Z',
        waitingTimeHours: 21.0,
        turnaroundTimeHours: 82.0,
        status: 'SCHEDULED',
      },
    ],
  },
];

export const DEMO_MARKET_DATA: MarketData = {
  balticDryIndex: {
    current: 1945,
    change: -28,
    changePercent: -1.42,
    trend: 'DOWN',
  },
  balticPanamaxIndex: {
    current: 1680,
    change: -34,
    changePercent: -1.98,
    trend: 'DOWN',
  },
  bunkerFuelVlsfoUsdPerMt: {
    singapore: 588.50,
    rotterdam: 546.00,
    fujairah: 574.00,
    trend: 'DOWN',
  },
  commoditiesUsdPerMt: {
    cokingCoal: 242.50,
    thermalCoal: 138.20,
    ironOre62Percent: 104.80,
  },
  lastUpdated: new Date().toISOString(),
};

export const DEMO_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'AI Freight Drop Signal',
    message: 'Panamax freight rates on Australia-Paradip route forecasted to decline 4.2% over next 72h.',
    type: 'FREIGHT_ALERT',
    severity: 'INFO',
    createdAt: '10 minutes ago',
    isRead: false,
    linkUrl: '/forecasts',
  },
  {
    id: 'notif-2',
    title: 'New Charter Offer Received',
    message: 'Oceanic Bulk Carrier Fleet submitted offer for 75,000 MT Coal (MV OCEAN FORTUNE @ $23.75/MT).',
    type: 'CHARTER_OFFER',
    severity: 'SUCCESS',
    createdAt: '45 minutes ago',
    isRead: false,
    linkUrl: '/charters',
  },
  {
    id: 'notif-3',
    title: 'Port Congestion Alert: Paradip',
    message: 'Paradip waiting time currently at 34.5 hours with 7 vessels anchored. Projected to ease by Sept 02.',
    type: 'CONGESTION_ALERT',
    severity: 'WARNING',
    createdAt: '2 hours ago',
    isRead: true,
    linkUrl: '/congestion/port-paradip',
  },
  {
    id: 'notif-4',
    title: 'AIS Position Update: MV PACIFIC PIONEER',
    message: 'Vessel entered Coral Sea passage, ETA revised to 14 Sep 08:00 UTC.',
    type: 'VESSEL_ETA_CHANGE',
    severity: 'INFO',
    createdAt: '4 hours ago',
    isRead: true,
    linkUrl: '/voyages',
  },
];

export const DEMO_KPIS = {
  activeCargoRequirements: 4,
  matchedVesselsAvailable: 3,
  currentMarketSpotRateUsdPerMt: 24.5,
  projectedSavingsUsd: 240000,
  averageLaycanWindowDays: 7,
  totalVolumeUnderTenderMt: 245000,
};

